[package]
name = "girt"
version = "0.1.0"
edition = "2024"
authors = ["Josh McKinney"]
description = "An incremental, idiomatic Rust implementation of Git"
license = "MIT OR Apache-2.0"
keywords = ["git", "version-control", "repository"]
categories = ["development-tools"]

[dependencies]
flate2 = "1"
sha1 = "0.10"
tempfile = "3"
thiserror = "2"

[dev-dependencies]
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
rstest = { version = "0.27.0", default-features = false }

[[bench]]
name = "blobs"
harness = false

[[example]]
name = "loose_blob"
doc-scrape-examples = true

[[bench]]
name = "trees"
harness = false

[[example]]
name = "tree"
doc-scrape-examples = true

[[example]]
name = "loose_tree"
doc-scrape-examples = true

[[bench]]
name = "loose_trees"
harness = false

[[example]]
name = "loose_commit"
doc-scrape-examples = true

[[bench]]
name = "commits"
harness = false

[[example]]
name = "loose_tag"
doc-scrape-examples = true

[[bench]]
name = "tags"
harness = false

[[example]]
name = "open_repository"
doc-scrape-examples = true

[[bench]]
name = "repositories"
harness = false

[[example]]
name = "publish_branch"
doc-scrape-examples = true

[[bench]]
name = "references"
harness = false
